In [1]:
import numpy as np
empty_array = np.empty((2,2))
print(empty_array)

[[4.79808584e-310 0.00000000e+000]
 [3.45845952e-323             nan]]


In [2]:
import numpy as np
ones_array = np.ones((2,2))
print(ones_array)

[[1. 1.]
 [1. 1.]]


In [3]:
import numpy as np
filled_array = np.full((2,2), 3.14)
print(filled_array)

[[3.14 3.14]
 [3.14 3.14]]


In [4]:
import numpy as np
def zeros_array(arr):
  return np.zeros_like(arr)


arr = np.array([[1,2,3],[4,5,6]])
zeros_array = zeros_array(arr)
print(zeros_array)

[[0 0 0]
 [0 0 0]]


In [5]:
import numpy as np

def ones_like(arr):
  return np.ones_like(arr)

arr = np.array([[1, 2, 3], [4, 5, 6]])
new_arr = ones_like(arr)
print(new_arr)

[[1 1 1]
 [1 1 1]]


In [6]:
import numpy as np

def ones_like(arr):
  return np.ones_like(arr)

arr = np.array([[1,2],[4,5]])
ones_array = ones_like(arr)
print(ones_array)

[[1 1]
 [1 1]]


In [7]:
import numpy as np

new_list = [1,2,3,4]
new_array = np.array(new_list)
print(new_array)

[1 2 3 4]


In [8]:
import numpy as np

range_array = np.arange(10,49)
print(range_array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [9]:
import numpy as np
matrix_array = np.arange(9).reshape((3,3))
print(matrix_array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [10]:
import numpy as np

new_identity_matrix = np.eye(3)
print(new_identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
import numpy as np

random_array = np.random.random(30)
mean_of_array = random_array.mean()
print(mean_of_array)

0.52217346437945


In [12]:
import numpy as np

random_array = np.random.random(100).reshape((10,10))
max_of_array = random_array.max()
min_of_array = random_array.min()
print(random_array)
print(max_of_array)
print(min_of_array)

[[0.04224802 0.28511921 0.90039572 0.39644877 0.34707328 0.83274385
  0.61008462 0.86306989 0.1963574  0.21244019]
 [0.77733671 0.13313537 0.95524617 0.59230633 0.4204064  0.23736949
  0.05716122 0.21428486 0.90762485 0.27225388]
 [0.67884398 0.76745434 0.96015933 0.83917033 0.44858732 0.69340602
  0.3956596  0.64628598 0.88738145 0.45781124]
 [0.4960727  0.48181899 0.28578048 0.22985769 0.00486797 0.53765027
  0.36646354 0.07810323 0.41622391 0.68127055]
 [0.32522766 0.21041167 0.87284983 0.48983937 0.58810356 0.68828523
  0.73208507 0.8029663  0.16767245 0.22407761]
 [0.49540145 0.7350142  0.72532607 0.29262592 0.33158807 0.54650631
  0.40039927 0.31218696 0.67068141 0.36791357]
 [0.40856262 0.85154122 0.49785497 0.95502711 0.49498989 0.59728588
  0.23000822 0.45229762 0.16115269 0.52621857]
 [0.53604065 0.30189323 0.38171689 0.79750155 0.41586739 0.67018696
  0.07609217 0.28990946 0.93860099 0.09542107]
 [0.72593773 0.91258137 0.24729579 0.75020409 0.53132799 0.9026406
  0.27921746 

In [13]:
import numpy as np

zeros_array = np.zeros(10)
zeros_array[4] = 1
print(zeros_array)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [14]:
import numpy as np

arr = [1,2,0,0,4,0]
arr.reverse()
print(arr)

[0, 4, 0, 0, 2, 1]


In [15]:
import numpy as np

arr = np.zeros((5, 5))
arr[0, :] = 1
arr[-1, :] = 1
arr[:, 0] = 1
arr[:, -1] = 1
print(arr)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [16]:
import numpy as np

checkerboard = np.zeros((8, 8))
checkerboard[::2, ::2] = 1
checkerboard[::2, 1::2] = 1
checkerboard[1::2, ::2] = 1
checkerboard[1::2, 1::2] = 0
print(checkerboard)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [17]:
import numpy as np

x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

addition_of_array = x+y
subtraction_of_array = v-w
multiplication_of_array = 3 * x
square_of_array = y**2
dot_product = np.dot(v,w)
another_dot_product = np.dot(x,v)
last_dot_product = np.dot(x,y)
print("Addition: ", addition_of_array)
print("Subtraction: ",subtraction_of_array)
print("Multiplication: ", multiplication_of_array)
print("Square: ",square_of_array)
print("Dot Product v and w: ", dot_product)
print("Dot Product x and v: ", another_dot_product)
print("Dot Product x and y: ", last_dot_product)


Addition:  [[ 6  8]
 [10 13]]
Subtraction:  [-2 -2]
Multiplication:  [[ 3  6]
 [ 9 15]]
Square:  [[25 36]
 [49 64]]
Dot Product v and w:  219
Dot Product x and v:  [29 77]
Dot Product x and y:  [[19 22]
 [50 58]]


In [18]:
import numpy as np

x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

xy_row = np.concatenate((x, y), axis=0)
vw_column = np.concatenate((v.reshape(2,1), w.reshape(2,1)), axis=1)

print("Concatenated x and y along row: \n", xy_row)
print("Concatenated v and w along column: \n", vw_column)


Concatenated x and y along row: 
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenated v and w along column: 
 [[ 9 11]
 [10 12]]
